"""Adiciona coluna quantidade_inicial a Produto

Revision ID: 3cc49f2d4d2b
Revises: 941b50331576
Create Date: 2025-07-11 08:05:59.533667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc49f2d4d2b'
down_revision = '941b50331576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_inicial', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('quantidade_inicial')

    # ### end Alembic commands ###
