"""Adiciona status_retorno

Revision ID: 72e97de0a953
Revises: d36a8f655207
Create Date: 2025-12-16 13:21:49.291453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e97de0a953'
down_revision = 'd36a8f655207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saida_materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_retorno', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saida_materiais', schema=None) as batch_op:
        batch_op.drop_column('status_retorno')

    # ### end Alembic commands ###
