"""Adiciona campo patrimonio_ativo para solicitacoes

Revision ID: d36a8f655207
Revises: e2208fe4ebe1
Create Date: 2025-07-17 11:39:27.691015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36a8f655207'
down_revision = 'e2208fe4ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patrimonio_ativo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('patrimonio_ativo')

    # ### end Alembic commands ###
