"""Adiciona tabela de anexos para fotos

Revision ID: e2208fe4ebe1
Revises: 3cc49f2d4d2b
Create Date: 2025-07-14 12:16:05.384946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2208fe4ebe1'
down_revision = '3cc49f2d4d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_anexo', sa.String(length=10), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexos')
    # ### end Alembic commands ###
